services:
  - type: web
    name: prisionero-game-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
